-- Active: 1699777386631@@127.0.0.1@3306@assignment6

-- Write a SQL query to retrieve the total revenue generated by each product category. Display the category name along with the total revenue in descending order of the revenue

SELECT
    c.name as Name,
    SUM(oi.quantity * oi.unit_price ) as Revenue
FROM 
    categories c 
JOIN
    products p ON c.id=p.category_id
JOIN 
    order_items oi ON p.id=oi.product_id 
GROUP BY 
    c.name 
ORDER BY 
    Revenue DESC;
